export const WORLD_COUNTRY_FLAG_ISO: Record<string, string> = {
	'United States': 'us',
	Canada: 'ca',
	'New Zealand': 'nz',
	Australia: 'au',
	Switzerland: 'ch',
	Peru: 'pe',
	Chile: 'cl',
	Brazil: 'br',
	Korea: 'kr',
	Italy: 'it',
	Ireland: 'ie',
	Singapore: 'sg',
	Uganda: 'ug',
	'United Kingdom': 'gb',
	Germany: 'de',
	Norway: 'no',
	'Trinidad & Tobago': 'tt',
};
